// Master Data — Akara Resources
// Source: Master_Level spreadsheet

export const DIVISIONS = [
  { code: "L1-001", name: "Kingsgate", nameTH: "คิงส์เกต" },
  { code: "L1-002", name: "Sustainability", nameTH: "ความยั่งยืนขององค์กร" },
  { code: "L1-003", name: "Operations", nameTH: "ปฎิบัติการ" },
  { code: "L1-004", name: "Exploration", nameTH: "สำรวจ" },
  { code: "L1-005", name: "Commercial", nameTH: "การพาณิชย์" },
];

export const DEPARTMENTS = [
  { code: "L2-001", name: "Environment", nameTH: "สิ่งแวดล้อม" },
  { code: "L2-002", name: "Processing", nameTH: "ผลิต" },
  { code: "L2-003", name: "Exploration", nameTH: "สำรวจ" },
  { code: "L2-004", name: "Community Relations & Development", nameTH: "ชุมชนสัมพันธ์และการพัฒนา" },
  { code: "L2-005", name: "Special Projects", nameTH: "โครงการพิเศษ" },
  { code: "L2-006", name: "Mining", nameTH: "เหมืองแร่" },
  { code: "L2-007", name: "Laboratory", nameTH: "ห้องปฏิบัติการทดสอบ" },
  { code: "L2-008", name: "Finance & Accounting", nameTH: "การเงินและบัญชี" },
  { code: "L2-009", name: "Supply", nameTH: "จัดซื้อ" },
  { code: "L2-010", name: "Administration", nameTH: "ธุรการ" },
  { code: "L2-011", name: "Information Technology", nameTH: "เทคโนโลยีสารสนเทศ" },
  { code: "L2-012", name: "Regulatory Affairs", nameTH: "งานอนุญาต" },
  { code: "L2-013", name: "Science & Health", nameTH: "วิทยาศาสตร์และสุขภาพ" },
  { code: "L2-014", name: "Communications", nameTH: "สื่อสารองค์กร" },
  { code: "L2-015", name: "Occupational Health & Safety", nameTH: "อาชีวอนามัยและความปลอดภัย" },
  { code: "L2-016", name: "Human Resources", nameTH: "ทรัพยากรบุคคล" },
  { code: "L2-017", name: "Land Management", nameTH: "บริหารที่ดิน" },
  { code: "L2-018", name: "Legal", nameTH: "กฎหมาย" },
];

export const SECTIONS = [
  { code: "L3-001", name: "Environment", nameTH: "สิ่งแวดล้อม" },
  { code: "L3-002", name: "Process", nameTH: "ผลิต" },
  { code: "L3-003", name: "Exploration", nameTH: "สำรวจ" },
  { code: "L3-004", name: "Community Relations & Development", nameTH: "ชุมชนสัมพันธ์และการพัฒนา" },
  { code: "L3-005", name: "Special Projects", nameTH: "โครงการพิเศษ" },
  { code: "L3-006", name: "Geology", nameTH: "ธรณีวิทยา" },
  { code: "L3-007", name: "Laboratory", nameTH: "ห้องปฏิบัติการทดสอบ" },
  { code: "L3-008", name: "Finance & Accounting", nameTH: "การเงินและบัญชี" },
  { code: "L3-009", name: "Maintenance", nameTH: "ซ่อมบำรุง" },
  { code: "L3-010", name: "Mining Operation", nameTH: "ปฏิบัติการเหมืองแร่" },
  { code: "L3-011", name: "Purchasing", nameTH: "จัดซื้อ" },
  { code: "L3-012", name: "Administration", nameTH: "ธุรการ" },
  { code: "L3-013", name: "Information Technology", nameTH: "เทคโนโลยีสารสนเทศ" },
  { code: "L3-014", name: "Permitting", nameTH: "งานอนุญาต" },
  { code: "L3-015", name: "Warehouse", nameTH: "คลังพัสดุ" },
  { code: "L3-016", name: "Science & Health", nameTH: "วิทยาศาสตร์และสุขภาพ" },
  { code: "L3-017", name: "Communications", nameTH: "สื่อสารองค์กร" },
  { code: "L3-018", name: "Occupational Health & Safety", nameTH: "อาชีวอนามัยและความปลอดภัย" },
  { code: "L3-019", name: "Mine Planning", nameTH: "วางแผนการทำเหมือง" },
  { code: "L3-020", name: "Human Resources Development", nameTH: "พัฒนาทรัพยากรบุคคล" },
  { code: "L3-021", name: "Human Resources Management", nameTH: "บริหารงานทรัพยากรบุคคล" },
  { code: "L3-022", name: "Compensation & Benefits", nameTH: "ค่าตอบแทนและสวัสดิการ" },
  { code: "L3-023", name: "Metallurgy", nameTH: "โลหวิทยา" },
  { code: "L3-024", name: "Land Management", nameTH: "บริหารที่ดิน" },
  { code: "L3-025", name: "Sustainable Development", nameTH: "พัฒนาความยั่งยืน" },
  { code: "L3-026", name: "Government Relations", nameTH: "รัฐกิจสัมพันธ์" },
  { code: "L3-027", name: "Chatree North", nameTH: "ชาตรีเหนือ" },
  { code: "L3-028", name: "Legal", nameTH: "กฎหมาย" },
];

export const TEAMS = [
  { code: "L4-001", name: "Environment", nameTH: "สิ่งแวดล้อม" },
  { code: "L4-002", name: "Process", nameTH: "ผลิต" },
  { code: "L4-003", name: "Exploration", nameTH: "สำรวจ" },
  { code: "L4-004", name: "Community Relations & Development", nameTH: "ชุมชนสัมพันธ์และการพัฒนา" },
  { code: "L4-005", name: "Special Projects", nameTH: "โครงการพิเศษ" },
  { code: "L4-006", name: "Geology", nameTH: "ธรณีวิทยา" },
  { code: "L4-007", name: "Laboratory", nameTH: "ห้องปฏิบัติการทดสอบ" },
  { code: "L4-008", name: "Finance & Accounting", nameTH: "การเงินและบัญชี" },
  { code: "L4-009", name: "Mechanical", nameTH: "ช่างกลและช่างเชื่อม" },
  { code: "L4-010", name: "Mining Operation", nameTH: "ปฏิบัติการเหมืองแร่" },
  { code: "L4-011", name: "Purchasing", nameTH: "จัดซื้อ" },
  { code: "L4-012", name: "Electrical", nameTH: "ไฟฟ้า" },
  { code: "L4-013", name: "Administration", nameTH: "ธุรการ" },
  { code: "L4-014", name: "Information Technology", nameTH: "เทคโนโลยีสารสนเทศ" },
  { code: "L4-015", name: "Permitting", nameTH: "งานอนุญาต" },
  { code: "L4-016", name: "Warehouse", nameTH: "คลังพัสดุ" },
  { code: "L4-017", name: "Science & Health", nameTH: "วิทยาศาสตร์และสุขภาพ" },
  { code: "L4-018", name: "Communications", nameTH: "สื่อสารองค์กร" },
  { code: "L4-019", name: "Occupational Health & Safety", nameTH: "อาชีวอนามัยและความปลอดภัย" },
  { code: "L4-020", name: "Civil", nameTH: "โยธา" },
  { code: "L4-021", name: "Mine Planning", nameTH: "วางแผนการทำเหมือง" },
  { code: "L4-022", name: "Human Resources Development", nameTH: "พัฒนาทรัพยากรบุคคล" },
  { code: "L4-023", name: "Human Resources", nameTH: "บริหารงานทรัพยากรบุคคล" },
  { code: "L4-024", name: "Compensation & Benefits", nameTH: "ค่าตอบแทนและสวัสดิการ" },
  { code: "L4-025", name: "Network Infrastructure", nameTH: "บริหารงานโครงข่ายพื้นฐาน" },
  { code: "L4-026", name: "Planning", nameTH: "วางแผนการผลิต" },
  { code: "L4-027", name: "Metallurgy", nameTH: "โลหวิทยา" },
  { code: "L4-028", name: "Land Management", nameTH: "บริหารที่ดิน" },
  { code: "L4-029", name: "Sustainable Development", nameTH: "พัฒนาความยั่งยืน" },
  { code: "L4-030", name: "Digital Transformation", nameTH: "พัฒนาระบบงานดิจิทัล" },
  { code: "L4-031", name: "Government Relations", nameTH: "รัฐกิจสัมพันธ์" },
  { code: "L4-032", name: "Project", nameTH: "โครงการ" },
  { code: "L4-033", name: "Chatree North", nameTH: "ชาตรีเหนือ" },
  { code: "L4-034", name: "Legal", nameTH: "กฎหมาย" },
  { code: "L4-035", name: "Mechanical", nameTH: "ช่างกลและช่างเชื่อม" },
];

export const POSITIONS = [
  { code: "P-001", name: "Ancillary Trainer" },
  { code: "P-002", name: "Document Translator (Contract)" },
  { code: "P-003", name: "Mobile Equipment Trainer" },
  { code: "P-004", name: "Senior Mobile Maintenance Planning Superintendent" },
  { code: "P-005", name: "Permitting Officer", nameTH: "เจ้าหน้าที่แผนกงานอนุญาต" },
  { code: "P-006", name: "Purchasing Officer", nameTH: "เจ้าหน้าที่แผนกจัดซื้อ" },
  { code: "P-007", name: "Community Relations Officer", nameTH: "เจ้าหน้าที่แผนกชุมชนสัมพันธ์" },
  { code: "P-008", name: "Community Relations & Development Officer", nameTH: "เจ้าหน้าที่แผนกชุมชนสัมพันธ์และการพัฒนา" },
  { code: "P-009", name: "Senior Community Relations & Development Officer" },
  { code: "P-010", name: "Sustainable Development Officer" },
  { code: "P-011", name: "Senior Sustainable Development Officer" },
  { code: "P-012", name: "Government Relations Officer" },
  { code: "P-013", name: "Occupational Health & Safety Data Clerk" },
  { code: "P-014", name: "Document Controller", nameTH: "เจ้าหน้าที่ควบคุมเอกสาร" },
  { code: "P-015", name: "FMS Dispatcher" },
  { code: "P-016", name: "Safety Officer", nameTH: "เจ้าหน้าที่ความปลอดภัย" },
  { code: "P-017", name: "Senior Safety Officer" },
  { code: "P-018", name: "Administrative & Communications Officer" },
  { code: "P-019", name: "Network Support Specialist" },
  { code: "P-020", name: "Digital Transformation Specialist" },
  { code: "P-021", name: "BOI Officer" },
  { code: "P-022", name: "Maintenance Administrator" },
  { code: "P-023", name: "Receptionist", nameTH: "เจ้าหน้าที่ประชาสัมพันธ์" },
  { code: "P-024", name: "Fund Coordinator" },
  { code: "P-025", name: "Senior Maintenance Coordinator" },
  { code: "P-026", name: "HR Officer", nameTH: "เจ้าหน้าที่ฝ่ายทรัพยากรบุคคล" },
  { code: "P-027", name: "Administrative Officer" },
  { code: "P-028", name: "Senior Administrative Officer" },
  { code: "P-029", name: "Accounting Officer" },
  { code: "P-030", name: "Senior Accounting Officer" },
  { code: "P-031", name: "Science & Health Officer" },
  { code: "P-032", name: "Senior Science & Health Officer" },
  { code: "P-033", name: "Communications Officer" },
  { code: "P-034", name: "Senior Digital Transformation" },
  { code: "P-035", name: "Senior Surveyor" },
  { code: "P-036", name: "Laboratory Technician", nameTH: "เจ้าหน้าที่ห้องปฏิบัติการทดสอบ" },
  { code: "P-037", name: "Senior Occupational Health & Safety Officer" },
  { code: "P-038", name: "Electrician", nameTH: "ช่างไฟฟ้า" },
  { code: "P-039", name: "Mechanic & Welder", nameTH: "ช่างกลและช่างเชื่อม" },
  { code: "P-040", name: "Mechanical Fitter" },
  { code: "P-041", name: "Junior Survey" },
  { code: "P-042", name: "Boiler Maker & Welder" },
  { code: "P-043", name: "Legal Counsel", nameTH: "ที่ปรึกษากฎหมาย" },
  { code: "P-044", name: "Senior Chemist" },
  { code: "P-045", name: "Senior Chemist Supervisor" },
  { code: "P-046", name: "Metallurgists" },
  { code: "P-047", name: "Senior Metallurgists" },
  { code: "P-048", name: "Senior Geotechnical Engineer" },
  { code: "P-049", name: "Geologist", nameTH: "นักธรณีวิทยา" },
  { code: "P-050", name: "Junior Geologist" },
  { code: "P-051", name: "Junior Geologist - Database" },
  { code: "P-052", name: "Senior Mining Engineer Specialist" },
  { code: "P-053", name: "General Manager - Operations" },
  { code: "P-054", name: "General Manager Sustainability" },
  { code: "P-055", name: "General Manager Operations" },
  { code: "P-056", name: "IT Manager" },
  { code: "P-057", name: "Mining Manager" },
  { code: "P-058", name: "Finance & Accounting Manager" },
  { code: "P-059", name: "Regulatory Affairs Manager" },
  { code: "P-060", name: "Supply Manager" },
  { code: "P-061", name: "Community Relations & Development Manager" },
  { code: "P-062", name: "Human Resources Manager" },
  { code: "P-063", name: "Administration Manager" },
  { code: "P-064", name: "Processing Manager" },
  { code: "P-065", name: "Exploration Manager" },
  { code: "P-066", name: "Regional Exploration Manager" },
  { code: "P-067", name: "Environmental Manager" },
  { code: "P-068", name: "Communications & Executive Support Manager" },
  { code: "P-069", name: "Laboratory Manager" },
  { code: "P-070", name: "Occupational Health & Safety Manager" },
  { code: "P-071", name: "Senior Exploration Manager" },
  { code: "P-072", name: "Database Assistant" },
  { code: "P-073", name: "Survey Assistant" },
  { code: "P-074", name: "Geological Assistant" },
  { code: "P-075", name: "Geology Assistant" },
  { code: "P-076", name: "Senior Geological Assistant" },
  { code: "P-077", name: "Exploration Coordinator Assistant" },
  { code: "P-078", name: "Mining Superintendent" },
  { code: "P-079", name: "Metallurgical Superintendent" },
  { code: "P-080", name: "Senior Maintenance Superintendent" },
  { code: "P-081", name: "Geology Superintendent" },
  { code: "P-082", name: "Senior Geology Superintendent" },
  { code: "P-083", name: "Accounting Superintendent" },
  { code: "P-084", name: "Accounting Superintendent-General Ledger" },
  { code: "P-085", name: "Process Operation Superintendent" },
  { code: "P-086", name: "Chatree North Superintendent" },
  { code: "P-087", name: "Mobile Maintenance Superintendent" },
  { code: "P-088", name: "Assistant Manager - Government Relations" },
  { code: "P-089", name: "Mine Planning Superintendent" },
  { code: "P-090", name: "Mine Operations & Maintenance Training Superintendent" },
  { code: "P-091", name: "Civil and Dewatering Superintendent" },
  { code: "P-092", name: "Senior Mine Operations Superintendent" },
  { code: "P-093", name: "Finance & Accounting Superintendent" },
  { code: "P-094", name: "Assistant Manager - Science & Health" },
  { code: "P-095", name: "Occupational Health & Safety Superintendent" },
  { code: "P-096", name: "Planning Superintendent" },
  { code: "P-097", name: "Exploration Coordinator" },
  { code: "P-098", name: "Dewatering Crew", nameTH: "พนักงานเหมืองแร่" },
  { code: "P-099", name: "Community Relations & Development Operator" },
  { code: "P-100", name: "Day Crew Operator" },
  { code: "P-101", name: "Project Staff" },
  { code: "P-102", name: "Shift Operator" },
  { code: "P-103", name: "Fuel Service Crew" },
  { code: "P-104", name: "Storeman" },
  { code: "P-105", name: "Maintenance Storeman" },
  { code: "P-106", name: "Senior Storeman" },
  { code: "P-107", name: "Maintenance Clerk" },
  { code: "P-108", name: "Mining Clerk" },
  { code: "P-109", name: "Operation Clerk" },
  { code: "P-110", name: "Soil Testing Assistant" },
  { code: "P-111", name: "General Support Operator" },
  { code: "P-112", name: "Science & Health Staff" },
  { code: "P-113", name: "Environmental Staff" },
  { code: "P-114", name: "Maintenance Planner" },
  { code: "P-115", name: "Met Lab Technician" },
  { code: "P-116", name: "Gold Room Operator" },
  { code: "P-117", name: "Laboratory Staff" },
  { code: "P-118", name: "Mechanical Engineer" },
  { code: "P-119", name: "Senior Mechanical Engineer" },
  { code: "P-120", name: "Instrument Engineer" },
  { code: "P-121", name: "Junior Drill & Blast Engineer" },
  { code: "P-122", name: "Mining Engineer" },
  { code: "P-123", name: "Junior Mining Engineer" },
  { code: "P-124", name: "Senior Mining Engineer" },
  { code: "P-125", name: "Electrical Engineer" },
  { code: "P-126", name: "Senior Project Engineer" },
  { code: "P-127", name: "Senior Network Engineer" },
  { code: "P-128", name: "Junior Civil Engineer" },
  { code: "P-129", name: "Mine Compliance Engineer" },
  { code: "P-130", name: "Senior Mine Compliance Engineer" },
  { code: "P-131", name: "Senior Environmental Engineer" },
  { code: "P-132", name: "Planning Engineer" },
  { code: "P-133", name: "Senior Planning Engineer" },
  { code: "P-134", name: "Senior Electrical Engineer" },
  { code: "P-135", name: "Gold Room Leading Hand" },
  { code: "P-136", name: "IT Supervisor" },
  { code: "P-137", name: "Mining Supervisor" },
  { code: "P-138", name: "Warehouse Supervisor" },
  { code: "P-139", name: "Compensation & Benefits Supervisor" },
  { code: "P-140", name: "Senior Contract Supervisor" },
  { code: "P-141", name: "Environmental Supervisor" },
  { code: "P-142", name: "Permitting Supervisor" },
  { code: "P-143", name: "Purchasing Supervisor" },
  { code: "P-144", name: "Senior Purchasing Supervisor" },
  { code: "P-145", name: "Senior Database Supervisor" },
  { code: "P-146", name: "Senior Human Resources Supervisor" },
  { code: "P-147", name: "Land Supervisor" },
  { code: "P-148", name: "Accounting Supervisor" },
  { code: "P-149", name: "Process Operation Supervisor" },
  { code: "P-150", name: "Senior Process Operation Supervisor" },
  { code: "P-151", name: "HRD Supervisor" },
  { code: "P-152", name: "Gold Room Supervisor" },
  { code: "P-153", name: "Occupational Health & Safety Supervisor" },
  { code: "P-154", name: "Senior Safety Supervisor" },
  { code: "P-155", name: "Head of Special Projects" },
  { code: "P-156", name: "Mine Shift Supervisor" },
  { code: "P-157", name: "Shift Supervisor" },
  { code: "P-158", name: "Shift Chemist" },
  { code: "P-159", name: "Compliance and Permitting Supervisor" },
  { code: "P-160", name: "HRIS Supervisor" },
  { code: "P-161", name: "Senior Geologist - Database" },
  { code: "P-162", name: "Senior Geologist" },
  { code: "P-163", name: "Head of Commercial" },
  { code: "P-164", name: "Chief Geologist & Land Manager" },
  { code: "P-165", name: "Environmental Engineer Supervisor" },
  { code: "P-166", name: "Day Crew Supervisor" },
  { code: "P-167", name: "Shift Leading Hand" },
  { code: "P-168", name: "Electrical Leading Hand" },
  { code: "P-169", name: "Mechanical Leading Hand" },
  { code: "P-170", name: "Environmental Leading Hand" },
  { code: "P-171", name: "Met Lab Leading Hand" },
  { code: "P-172", name: "Leading Hand" },
  { code: "P-173", name: "Laboratory Leading Hand" },
  { code: "P-174", name: "Senior Permitting Supervisor" },
  { code: "P-175", name: "Engineer Control Systems" },
  { code: "P-176", name: "Instrumentation Engineer" },
  { code: "P-177", name: "Site Services Supervisor" },
  { code: "P-178", name: "Senior Drill & Blast Engineer" },
  { code: "P-179", name: "TSF Supervisor" },
  { code: "P-180", name: "Senior Short & Mid Term Engineer" },
  { code: "P-181", name: "Geological Leading Hand" },
  { code: "P-182", name: "Senior Technical Services Superintendent" },
  { code: "P-183", name: "Senior Warehouse Supervisor" },
  { code: "P-184", name: "Accountant", nameTH: "เจ้าหน้าที่บัญชี" },
  { code: "P-185", name: "Legal Counsel and Compliance Officer" },
  { code: "P-186", name: "Mechanical Superintendent" },
];

export const JOB_LEVELS = [
  { code: "M1", name: "M1" },
  { code: "M2", name: "M2" },
  { code: "M3", name: "M3" },
  { code: "M4", name: "M4" },
  { code: "O1", name: "O1" },
  { code: "O2", name: "O2" },
  { code: "O3", name: "O3" },
  { code: "S1", name: "S1" },
  { code: "S2", name: "S2" },
  { code: "S3", name: "S3" },
];

export const SITES = ["Chatree", "Chatree North", "Vientiane Office", "Bangkok Office", "Other"];
export const CONTRACT_TYPES = ["Permanent", "Contract", "Probation", "Outsource"];
export const NATIONALITIES = ["Thai", "Lao", "Australian", "Other"];
export const GENDERS = ["Male", "Female", "Other"];
export const EMP_STATUSES = ["Active", "Resigned", "Terminated", "Retired", "Transferred"];
