-- ============================================================
-- SEED: MASTER POSITIONS (186 ตำแหน่ง จาก Master_Level spreadsheet)
-- วิธีใช้: Supabase Dashboard > SQL Editor > วางทั้งหมด > Run
-- รันซ้ำได้: ถ้า code ซ้ำจะอัปเดตชื่อให้เป็นค่าล่าสุดแทน
-- ============================================================
insert into master_positions (code, name, name_th, sort_order) values
  ('P-001', 'Ancillary Trainer', null, 1),
  ('P-002', 'Document Translator (Contract)', null, 2),
  ('P-003', 'Mobile Equipment Trainer', null, 3),
  ('P-004', 'Senior Mobile Maintenance Planning Superintendent', null, 4),
  ('P-005', 'Permitting Officer', 'เจ้าหน้าที่แผนกงานอนุญาต', 5),
  ('P-006', 'Purchasing Officer', 'เจ้าหน้าที่แผนกจัดซื้อ', 6),
  ('P-007', 'Community Relations Officer', 'เจ้าหน้าที่แผนกชุมชนสัมพันธ์', 7),
  ('P-008', 'Community Relations & Development Officer', 'เจ้าหน้าที่แผนกชุมชนสัมพันธ์และการพัฒนา', 8),
  ('P-009', 'Senior Community Relations & Development Officer', 'เจ้าหน้าที่แผนกชุมชนสัมพันธ์และการพัฒนาอาวุโส', 9),
  ('P-010', 'Sustainable Development Officer', 'เจ้าหน้าที่แผนกพัฒนาความยั่งยืน', 10),
  ('P-011', 'Senior Sustainable Development Officer', 'เจ้าหน้าที่แผนกพัฒนาความยั่งยืนอาวุโส', 11),
  ('P-012', 'Government Relations Officer', 'เจ้าหน้าที่แผนกรัฐกิจสัมพันธ์', 12),
  ('P-013', 'Occupational Health & Safety Data Clerk', 'เจ้าหน้าที่ข้อมูลด้านอาชีวอนามัยและความปลอดภัย', 13),
  ('P-014', 'Document Controller', 'เจ้าหน้าที่ควบคุมเอกสาร', 14),
  ('P-015', 'FMS Dispatcher', 'เจ้าหน้าที่ควบคุมและติดตามยานพาหนะ (ระบบบริหารจัดการยานพาหนะ)', 15),
  ('P-016', 'Safety Officer', 'เจ้าหน้าที่ความปลอดภัย', 16),
  ('P-017', 'Senior Safety Officer', 'เจ้าหน้าที่ความปลอดภัยอาวุโส', 17),
  ('P-018', 'Administrative & Communications Officer', 'เจ้าหน้าที่งานธุรการและการสื่อสารองค์กร', 18),
  ('P-019', 'Network Support Specialist', 'เจ้าหน้าที่ชำนาญงานโครงข่ายพื้นฐาน', 19),
  ('P-020', 'Digital Transformation Specialist', 'เจ้าหน้าที่ชำนาญงานพัฒนาระบบงานดิจิทัล', 20),
  ('P-021', 'BOI Officer', 'เจ้าหน้าที่ดูแลงาน BOI', 21),
  ('P-022', 'Maintenance Administrator', 'เจ้าหน้าที่ธุรการ', 22),
  ('P-023', 'Receptionist', 'เจ้าหน้าที่ประชาสัมพันธ์', 23),
  ('P-024', 'Fund Coordinator', 'เจ้าหน้าที่ประสานงานกองทุน', 24),
  ('P-025', 'Senior Maintenance Coordinator', 'เจ้าหน้าที่ประสานงานซ่อมบำรุงอาวุโส', 25),
  ('P-026', 'HR Officer', 'เจ้าหน้าที่ฝ่ายทรัพยากรบุคคล', 26),
  ('P-027', 'Administrative Officer', 'เจ้าหน้าที่ฝ่ายธุรการ', 27),
  ('P-028', 'Senior Administrative Officer', 'เจ้าหน้าที่ฝ่ายธุรการอาวุโส', 28),
  ('P-029', 'Accounting Officer', 'เจ้าหน้าที่ฝ่ายบัญชี', 29),
  ('P-030', 'Senior Accounting Officer', 'เจ้าหน้าที่ฝ่ายบัญชีอาวุโส', 30),
  ('P-031', 'Science & Health Officer', 'เจ้าหน้าที่ฝ่ายวิทยาศาสตร์และสุขภาพ', 31),
  ('P-032', 'Senior Science & Health Officer', 'เจ้าหน้าที่ฝ่ายวิทยาศาสตร์และสุขภาพอาวุโส', 32),
  ('P-033', 'Communications Officer', 'เจ้าหน้าที่ฝ่ายสื่อสารองค์กร', 33),
  ('P-034', 'Senior Digital Transformation', 'เจ้าหน้าที่ระบบงานดิจิทัลอาวุโส', 34),
  ('P-035', 'Senior Surveyor', 'เจ้าหน้าที่รังวัดอาวุโส', 35),
  ('P-036', 'Laboratory Technician', 'เจ้าหน้าที่ห้องปฏิบัติการทดสอบ', 36),
  ('P-037', 'Senior Occupational Health & Safety Officer', 'เจ้าหน้าที่อาชีวอนามัยและความปลอดภัยอาวุโส', 37),
  ('P-038', 'Electrician', 'ช่างไฟฟ้า', 38),
  ('P-039', 'Mechanic & Welder', 'ช่างกลและช่างเชื่อม', 39),
  ('P-040', 'Mechanical Fitter', 'ช่างกลและช่างประกอบ', 40),
  ('P-041', 'Junior Survey', 'ช่างรังวัดระดับต้น', 41),
  ('P-042', 'Boiler Maker & Welder', 'ช่างหม้อไอน้ำและช่างเชื่อม', 42),
  ('P-043', 'Legal Counsel', 'ที่ปรึกษากฎหมาย', 43),
  ('P-044', 'Senior Chemist', 'นักเคมีอาวุโส', 44),
  ('P-045', 'Senior Chemist Supervisor', 'นักเคมีอาวุโส (ระดับหัวหน้าแผนก)', 45),
  ('P-046', 'Metallurgists', 'นักโลหวิทยา', 46),
  ('P-047', 'Senior Metallurgists', 'นักโลหวิทยาอาวุโส', 47),
  ('P-048', 'Senior Geotechnical Engineer', 'นักธรณีเทคนิคอาวุโส', 48),
  ('P-049', 'Geologist', 'นักธรณีวิทยา', 49),
  ('P-050', 'Junior Geologist', 'นักธรณีวิทยาระดับต้น', 50),
  ('P-051', 'Junior Geologist - Database', 'นักธรณีวิทยางานฐานข้อมูลระดับต้น', 51),
  ('P-052', 'Senior Mining Engineer Specialist', 'ผู้เชี่ยวชาญด้านวิศวกรเหมืองแร่อาวุโส', 52),
  ('P-053', 'General Manager - Operations', 'ผู้จัดการทั่วไป - ฝ่ายปฎิบัติการ', 53),
  ('P-054', 'General Manager Sustainability', 'ผู้จัดการทั่วไป ฝ่ายความยั่งยืนขององค์กร', 54),
  ('P-055', 'General Manager Operations', 'ผู้จัดการทั่วไปฝ่ายปฏิบัติการ', 55),
  ('P-056', 'IT Manager', 'ผู้จัดการฝ่ายเทคโนโลยีสารสนเทศ', 56),
  ('P-057', 'Mining Manager', 'ผู้จัดการฝ่ายเหมืองแร่', 57),
  ('P-058', 'Finance & Accounting Manager', 'ผู้จัดการฝ่ายการเงินและบัญชี', 58),
  ('P-059', 'Regulatory Affairs Manager', 'ผู้จัดการฝ่ายงานอนุญาต', 59),
  ('P-060', 'Supply Manager', 'ผู้จัดการฝ่ายจัดซื้อ', 60),
  ('P-061', 'Community Relations & Development Manager', 'ผู้จัดการฝ่ายชุมชนสัมพันธ์และการพัฒนา', 61),
  ('P-062', 'Human Resources Manager', 'ผู้จัดการฝ่ายทรัพยากรบุคคล', 62),
  ('P-063', 'Administration Manager', 'ผู้จัดการฝ่ายธุรการ', 63),
  ('P-064', 'Processing Manager', 'ผู้จัดการฝ่ายผลิต', 64),
  ('P-065', 'Exploration Manager', 'ผู้จัดการฝ่ายสำรวจ', 65),
  ('P-066', 'Regional Exploration Manager', 'ผู้จัดการฝ่ายสำรวจ (ระดับภูมิภาค)', 66),
  ('P-067', 'Environmental Manager', 'ผู้จัดการฝ่ายสิ่งแวดล้อม', 67),
  ('P-068', 'Communications & Executive Support Manager', 'ผู้จัดการฝ่ายสื่อสารองค์กรและสนับสนุนผู้บริหาร', 68),
  ('P-069', 'Laboratory Manager', 'ผู้จัดการฝ่ายห้องปฏิบัติการทดสอบ', 69),
  ('P-070', 'Occupational Health & Safety Manager', 'ผู้จัดการฝ่ายอาชีวอนามัยและความปลอดภัย', 70),
  ('P-071', 'Senior Exploration Manager', 'ผู้จัดการอาวุโสฝ่ายสำรวจ', 71),
  ('P-072', 'Database Assistant', 'ผู้ช่วยงานฐานข้อมูล', 72),
  ('P-073', 'Survey Assistant', 'ผู้ช่วยช่างรังวัด', 73),
  ('P-074', 'Geological Assistant', 'ผู้ช่วยนักธรณีวิทยา (สำรวจ)', 74),
  ('P-075', 'Geology Assistant', 'ผู้ช่วยนักธรณีวิทยา (ธรณีวิทยา)', 75),
  ('P-076', 'Senior Geological Assistant', 'ผู้ช่วยนักธรณีวิทยาอาวุโส', 76),
  ('P-077', 'Exploration Coordinator Assistant', 'ผู้ช่วยประสานงานฝ่ายสำรวจ', 77),
  ('P-078', 'Mining Superintendent', 'ผู้ช่วยผู้จัดการแผนกเหมืองแร่', 78),
  ('P-079', 'Metallurgical Superintendent', 'ผู้ช่วยผู้จัดการแผนกโลหวิทยา', 79),
  ('P-080', 'Senior Maintenance Superintendent', 'ผู้ช่วยผู้จัดการแผนกซ่อมบำรุงอาวุโส', 80),
  ('P-081', 'Geology Superintendent', 'ผู้ช่วยผู้จัดการแผนกธรณีวิทยา', 81),
  ('P-082', 'Senior Geology Superintendent', 'ผู้ช่วยผู้จัดการแผนกธรณีวิทยาอาวุโส', 82),
  ('P-083', 'Accounting Superintendent', 'ผู้ช่วยผู้จัดการแผนกบัญชี', 83),
  ('P-084', 'Accounting Superintendent-General Ledger', 'ผู้ช่วยผู้จัดการแผนกบัญชี-บัญชีทั่วไป', 84),
  ('P-085', 'Process Operation Superintendent', 'ผู้ช่วยผู้จัดการแผนกผลิต', 85),
  ('P-086', 'Chatree North Superintendent', 'ผู้ช่วยผู้จัดการแผนกผู้รับเหมาชาตรีเหนือ', 86),
  ('P-087', 'Mobile Maintenance Superintendent', 'ผู้ช่วยผู้จัดการแผนกผู้รับเหมาชาตรีเหนือ', 87),
  ('P-088', 'Assistant Manager - Government Relations', 'ผู้ช่วยผู้จัดการแผนกรัฐกิจสัมพันธ์', 88),
  ('P-089', 'Mine Planning Superintendent', 'ผู้ช่วยผู้จัดการแผนกวางแผนการทำเหมือง', 89),
  ('P-090', 'Mine Operations & Maintenance Training Superintendent', 'ผู้ช่วยผู้จัดการงานอบรมการดำเนินการและบำรุงรักษา', 90),
  ('P-091', 'Civil and Dewatering Superintendent', 'ผู้ช่วยผู้จัดการด้านโยธาและการจัดการน้ำ', 91),
  ('P-092', 'Senior Mine Operations Superintendent', 'ผู้ช่วยผู้จัดการฝ่ายเหมืองแร่อาวุโส', 92),
  ('P-093', 'Finance & Accounting Superintendent', 'ผู้ช่วยผู้จัดการฝ่ายการเงินและบัญชี', 93),
  ('P-094', 'Assistant Manager - Science & Health', 'ผู้ช่วยผู้จัดการฝ่ายวิทยาศาสตร์และสุขภาพ', 94),
  ('P-095', 'Occupational Health & Safety Superintendent', 'ผู้ช่วยผู้จัดการฝ่ายอาชีวอนามัยและความปลอดภัย', 95),
  ('P-096', 'Planning Superintendent', 'ผู้ช่วยผู้จัดการวางแผนการผลิต', 96),
  ('P-097', 'Exploration Coordinator', 'ผู้ประสานงานฝ่ายสำรวจอาวุโส', 97),
  ('P-098', 'Dewatering Crew', 'พนักงานเหมืองแร่', 98),
  ('P-099', 'Community Relations & Development Operator', 'พนักงานแผนกชุมชนสัมพันธ์และการพัฒนา', 99),
  ('P-100', 'Day Crew Operator', 'พนักงานแผนกผลิต', 100),
  ('P-101', 'Project Staff', 'พนักงานโครงการ', 101),
  ('P-102', 'Shift Operator', 'พนักงานกะแผนกผลิต', 102),
  ('P-103', 'Fuel Service Crew', 'พนักงานคลังน้ำมัน', 103),
  ('P-104', 'Storeman', 'พนักงานคลังพัสดุ', 104),
  ('P-105', 'Maintenance Storeman', 'พนักงานคลังพัสดุ แผนกซ่อมบำรุง', 105),
  ('P-106', 'Senior Storeman', 'พนักงานคลังพัสดุอาวุโส', 106),
  ('P-107', 'Maintenance Clerk', 'พนักงานธุรการ แผนกซ่อมบำรุง', 107),
  ('P-108', 'Mining Clerk', 'พนักงานธุรการ ฝ่ายเหมืองแร่', 108),
  ('P-109', 'Operation Clerk', 'พนักงานธุรการ ฝ่ายผลิต', 109),
  ('P-110', 'Soil Testing Assistant', 'พนักงานปฏิบัติการงานโยธา', 110),
  ('P-111', 'General Support Operator', 'พนักงานฝ่ายบริการทั่วไป', 111),
  ('P-112', 'Science & Health Staff', 'พนักงานฝ่ายวิทยาศาสตร์และสุขภาพ', 112),
  ('P-113', 'Environmental Staff', 'พนักงานฝ่ายสิ่งแวดล้อม', 113),
  ('P-114', 'Maintenance Planner', 'พนักงานวางแผนซ่อมบำรุง', 114),
  ('P-115', 'Met Lab Technician', 'พนักงานห้องทดสอบโลหวิทยา', 115),
  ('P-116', 'Gold Room Operator', 'พนักงานห้องทอง', 116),
  ('P-117', 'Laboratory Staff', 'พนักงานห้องปฏิบัติการทดสอบ', 117),
  ('P-118', 'Mechanical Engineer', 'วิศวกรเครื่องกล', 118),
  ('P-119', 'Senior Mechanical Engineer', 'วิศวกรเครื่องกลอาวุโส', 119),
  ('P-120', 'Instrument Engineer', 'วิศวกรเครื่องมือวัด', 120),
  ('P-121', 'Junior Drill & Blast Engineer', 'วิศวกรเจาะและระเบิดระดับต้น', 121),
  ('P-122', 'Mining Engineer', 'วิศวกรเหมืองแร่', 122),
  ('P-123', 'Junior Mining Engineer', 'วิศวกรเหมืองแร่ระดับต้น', 123),
  ('P-124', 'Senior Mining Engineer', 'วิศวกรเหมืองแร่อาวุโส', 124),
  ('P-125', 'Electrical Engineer', 'วิศวกรแผนกไฟฟ้า', 125),
  ('P-126', 'Senior Project Engineer', 'วิศวกรโครงการอาวุโส', 126),
  ('P-127', 'Senior Network Engineer', 'วิศวกรโครงข่ายพื้นฐานอาวุโส', 127),
  ('P-128', 'Junior Civil Engineer', 'วิศวกรโยธาระดับต้น', 128),
  ('P-129', 'Mine Compliance Engineer', 'วิศวกรกำกับการปฏิบัติงาน', 129),
  ('P-130', 'Senior Mine Compliance Engineer', 'วิศวกรกำกับการปฏิบัติงานอาวุโส', 130),
  ('P-131', 'Senior Environmental Engineer', 'วิศวกรฝ่ายสิ่งแวดล้อม', 131),
  ('P-132', 'Planning Engineer', 'วิศวกรวางแผนการผลิต', 132),
  ('P-133', 'Senior Planning Engineer', 'วิศวกรวางแผนการผลิตอาวุโส', 133),
  ('P-134', 'Senior Electrical Engineer', 'วิศวกรอาวุโสแผนกไฟฟ้า', 134),
  ('P-135', 'Gold Room Leading Hand', 'ห้วหน้าหน่วยงานห้องทอง', 135),
  ('P-136', 'IT Supervisor', 'หัวหน้าแผนกเทคโนโลยีสารทนเทศ', 136),
  ('P-137', 'Mining Supervisor', 'หัวหน้าแผนกเหมืองแร่', 137),
  ('P-138', 'Warehouse Supervisor', 'หัวหน้าแผนกคลังพัสดุ', 138),
  ('P-139', 'Compensation & Benefits Supervisor', 'หัวหน้าแผนกค่าตอบแทนและสวัสดิการ', 139),
  ('P-140', 'Senior Contract Supervisor', 'หัวหน้าแผนกงานบริหารสัญญาอาวุโส', 140),
  ('P-141', 'Environmental Supervisor', 'หัวหน้าแผนกงานสิ่งแวดล้อม', 141),
  ('P-142', 'Permitting Supervisor', 'หัวหน้าแผนกงานอนุญาต', 142),
  ('P-143', 'Purchasing Supervisor', 'หัวหน้าแผนกจัดซื้อ', 143),
  ('P-144', 'Senior Purchasing Supervisor', 'หัวหน้าแผนกจัดซื้ออาวุโส', 144),
  ('P-145', 'Senior Database Supervisor', 'หัวหน้าแผนกฐานข้อมูลอาวุโส ฝ่ายสำรวจ', 145),
  ('P-146', 'Senior Human Resources Supervisor', 'หัวหน้าแผนกทรัพยากรบุคคลอาวุโส', 146),
  ('P-147', 'Land Supervisor', 'หัวหน้าแผนกบริหารที่ดิน', 147),
  ('P-148', 'Accounting Supervisor', 'หัวหน้าแผนกบัญชี', 148),
  ('P-149', 'Process Operation Supervisor', 'หัวหน้าแผนกผลิต', 149),
  ('P-150', 'Senior Process Operation Supervisor', 'หัวหน้าแผนกผลิตอาวุโส', 150),
  ('P-151', 'HRD Supervisor', 'หัวหน้าแผนกพัฒนาทรัพยากรบุคคล', 151),
  ('P-152', 'Gold Room Supervisor', 'หัวหน้าแผนกห้องทอง', 152),
  ('P-153', 'Occupational Health & Safety Supervisor', 'หัวหน้าแผนกอาชีวอนามัยและความปลอดภัย', 153),
  ('P-154', 'Senior Safety Supervisor', 'หัวหน้าแผนกอาชีวอนามัยและความปลอดภัยอาวุโส', 154),
  ('P-155', 'Head of Special Projects', 'หัวหน้าโครงการพิเศษ', 155),
  ('P-156', 'Mine Shift Supervisor', 'หัวหน้ากะแผนกเหมืองแร่', 156),
  ('P-157', 'Shift Supervisor', 'หัวหน้ากะแผนกผลิต', 157),
  ('P-158', 'Shift Chemist', 'หัวหน้ากะงานเคมี', 158),
  ('P-159', 'Compliance and Permitting Supervisor', 'หัวหน้างานด้านระเบียบปฏิบัติและงานอนุญาต', 159),
  ('P-160', 'HRIS Supervisor', 'หัวหน้างานระบบสารสนเทศทรัพยากรบุคคล', 160),
  ('P-161', 'Senior Geologist - Database', 'หัวหน้างานอาวุโสแผนกฐานข้อมูลธรณีวิทยา ฝ่ายเหมืองแร่', 161),
  ('P-162', 'Senior Geologist', 'หัวหน้างานอาวุโสแผนกธรณีวิทยา', 162),
  ('P-163', 'Head of Commercial', 'หัวหน้าฝ่ายการพาณิชย์', 163),
  ('P-164', 'Chief Geologist & Land Manager', 'หัวหน้าฝ่ายธรณีวิทยาและที่ดิน', 164),
  ('P-165', 'Environmental Engineer Supervisor', 'หัวหน้าวิศวกรฝ่ายสิ่งแวดล้อม', 165),
  ('P-166', 'Day Crew Supervisor', 'หัวหน้าหน่วยงานแผนกผลิต', 166),
  ('P-167', 'Shift Leading Hand', 'หัวหน้าหน่วยงานแผนกผลิต', 167),
  ('P-168', 'Electrical Leading Hand', 'หัวหน้าหน่วยงานช่างไฟฟ้า', 168),
  ('P-169', 'Mechanical Leading Hand', 'หัวหน้าหน่วยงานช่างกล', 169),
  ('P-170', 'Environmental Leading Hand', 'หัวหน้าหน่วยงานสิ่งแวดล้อม', 170),
  ('P-171', 'Met Lab Leading Hand', 'หัวหน้าหน่วยงานห้องทดสอบโลหวิทยา', 171),
  ('P-172', 'Leading Hand', 'หัวหน้าหน่วยงานห้องปฎิบัติการทดสอบ 1', 172),
  ('P-173', 'Laboratory Leading Hand', 'หัวหน้าหน่วยงานห้องปฎิบัติการทดสอบ', 173),
  ('P-174', 'Senior Permitting Supervisor', 'หัวหน้าอาวุโสแผนกงานอนุญาต', 174),
  ('P-175', 'Engineer Control Systems', 'วิศวกรควบคุมระบบแผนกไฟฟ้า', 175),
  ('P-176', 'Instrumentation Engineer', 'วิศวกรเครื่องมือวัด', 176),
  ('P-177', 'Site Services Supervisor', 'หัวหน้างานบริการสนับสนุนส่วนหน้างาน', 177),
  ('P-178', 'Senior Drill & Blast Engineer', 'วิศวกรงานเจาะและระเบิดอาวุโส', 178),
  ('P-179', 'TSF Supervisor', 'หัวหน้างานปฏิบัติการพื้นที่กักเก็บกากแร่', 179),
  ('P-180', 'Senior Short & Mid Term Engineer', 'วิศวกรเหมืองแร่ด้านแผนระยะสั้นและระยะกลางอาวุโส', 180),
  ('P-181', 'Geological Leading Hand', 'หัวหน้าหน่วยงานธรณีวิทยา ฝ่ายสำรวจ', 181),
  ('P-182', 'Senior Technical Services Superintendent', 'ผู้ช่วยผู้จัดการบริการด้านเทคนิคอาวุโส', 182),
  ('P-183', 'Senior Warehouse Supervisor', 'หัวหน้าแผนกคลังพัสดุอาวุโส', 183),
  ('P-184', 'Accountant', 'เจ้าหน้าที่บัญชี', 184),
  ('P-185', 'Legal Counsel and Compliance Officer', 'ที่ปรึกษากฎหมายและเจ้าหน้าที่กำกับการปฏิบัติตามกฎหมาย', 185),
  ('P-186', 'Mechanical Superintendent', 'ผู้ช่วยผู้จัดการงานเครื่องกล', 186)
on conflict (code) do update set
  name = excluded.name,
  name_th = excluded.name_th,
  sort_order = excluded.sort_order,
  is_active = true;
